const express = require('express');
var router = express.Router();
const userController = require('./controller/userController');
const movieController = require('./controller/movieController');
const listController = require('./controller/listController');
router.route("/register").post(userController.register);
router.route("/login").post(userController.login);
router.route("/getusers").get(userController.getUsers);
router.route("/getUser/:id").get(userController.getUser);
router.route("/updateUser/:id").put(userController.updateUser);
router.route("/deleteUser/:id").delete(userController.deleteUser);
router.route("/getMovies").get(movieController.getMovies);
router.route("/getMovie/:id").get(movieController.getMovie);
router.route("/addMovie").post(movieController.addMovie);
router.route("/updateMovie/:id").put(movieController.updateMovie);
router.route("/deleteMovie/:id").delete(movieController.deleteMovie);
router.route("/getRandom").get(movieController.getRandom);
router.route("/getLists").get(listController.getLists);
router.route("/addList").post(listController.addList);
router.route("/deleteList/:id").delete(listController.deleteList);
module.exports=router;